# Generated by Django 5.1.2 on 2024-11-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0003_rename_nome_convidado_convidados_nome_convidados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convidados',
            old_name='nome_convidados',
            new_name='nome_convidado',
        ),
    ]
